### ISSUE TITLE
Recommend users to use the Melpa version

### ISSUE THREAD

**Issue by azzamsa** [catppuccin/emacs#107]
Hi.

I find Catppuccin on Melpa https://melpa.org/#/catppuccin-theme. But why does the README still teach us to use the `catppuccin-theme.el` file manually from this repo? Isn't this harder to pull the new changes?

**Comment by nyxkrage** [comment]
Hey, yeah you are absolutely right, this is just left over from before we had it on Melpa, feel free to open a PR changing the instructions, otherwise I'll get around to it at some point
