### ISSUE TITLE
No iedit faces specified (used by evil-multiedit)

### ISSUE THREAD

**Issue by azzamsa** [catppuccin/emacs#108]
Hi.

Dracula and Catppuccin have similar colors for highlighted words. It is grey. 
But unlike Catppuccin, Dracula changes its regions to a more noticeable color during evil-multiedit.

- Catppuccin. It is very hard to find the matching words.

![image](https://github.com/catppuccin/emacs/assets/17734314/9b69fdde-da5a-4679-b4d8-0325ecf47055)

- Dracula. It is very easy to spot the selected regions.

![image](https://github.com/catppuccin/emacs/assets/17734314/3922621f-06c7-44fa-bbe5-983cc25b75ec)

**Comment by nyxkrage** [comment]
Hey, yeah this should probably be changed to the same style as the `match` face with red background and mantle foreground.

Seems evil-multiedit uses the iedit faces, I'll update the title of the issue to reflect that its about adding iedit faces and by extension adding support for evil-multiedit.

The faces `iedit-occurrence` and `iedit-read-only-occurrence`, if you want to make a PR, it would be appreciated!
