### ISSUE TITLE
active region almost unnoticable 

### ISSUE THREAD

**Issue by azzamsa** [catppuccin/emacs#112]
Hi.

I think we need to make the active region brighter or bolder.
It is almost unnoticeable because when have current line highlighted.

![image](https://github.com/catppuccin/emacs/assets/17734314/30ed6077-d689-4bd3-967d-4de27370a928)

**Comment by azzamsa** [comment]
I changed it to:

```diff
modified   catppuccin-theme.el
@@ -323,7 +323,7 @@ Must be one of `mocha`, `macchiato`, `frappe`, or `latte`."
                (mode-line-inactive
                 :background ,ctp-crust :inverse-video nil :foreground ,ctp-overlay0)
                (read-multiple-choice-face :inherit completions-first-difference)
-               (region :background ,ctp-surface0 :extend t)
+               (region :background ,ctp-surface2 :extend t)
                (shadow :foreground ,ctp-overlay0)
                (success :foreground ,ctp-green)
```

![image](https://github.com/catppuccin/emacs/assets/17734314/6864724c-d044-41a3-bdfa-810cac2acb03)

**Comment by drishal** [comment]
> I changed it to:
> 
> ```diff
> modified   catppuccin-theme.el
> @@ -323,7 +323,7 @@ Must be one of `mocha`, `macchiato`, `frappe`, or `latte`."
>                 (mode-line-inactive
>                  :background ,ctp-crust :inverse-video nil :foreground ,ctp-overlay0)
>                 (read-multiple-choice-face :inherit completions-first-difference)
> -               (region :background ,ctp-surface0 :extend t)
> +               (region :background ,ctp-surface2 :extend t)
>                 (shadow :foreground ,ctp-overlay0)
>                 (success :foreground ,ctp-green)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/17734314/248402982-da9d20e1-8383-4d6c-ad47-d77235fed6bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODMxMjIsIm5iZiI6MTcwNTY4MjgyMiwicGF0aCI6Ii8xNzczNDMxNC8yNDg0MDI5ODItZGE5ZDIwZTEtODM4My00ZDZjLWFkNDctZDc3MjM1ZmVkNmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE2NDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjODY3Y2FiYjAyMDFkMDc5ODg5NDUwZTM1MWIyZGI2MTQxM2ZkMTZjZDc1YzY4NjQwYzhjMzJlOTZlMWExNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UhWIoIy8RTfzI-3s3UuREPle-smwuq2Mw3uHN8h6Rvo)

just a small query, it does not seem to be there in the repo?  (even I am struggling with this issue but not sure how to modify it myself) 
https://github.com/catppuccin/emacs/blob/main/catppuccin-theme.el#L345
