### ISSUE TITLE
Extemely small fonts when running Emacs Daemon

### ISSUE THREAD

**Issue by raskolnikov104** [catppuccin/emacs#117]
![Screenshot from 2023-08-04 22-33-09](https://github.com/catppuccin/emacs/assets/111840273/ab494771-bed5-476c-badb-b82a5f1fe80b)
Unreadable fonts for subsection in daemon mode(Emacsclient). Doesen't happen when Emacs is launched normally.

**Comment by uncomfyhalomacro** [comment]
@raskolnikov104 pls close this as that is not a catppuccin theming issue.
