### ISSUE TITLE
Font scaling issues

### ISSUE THREAD

**Issue by artemisYo** [catppuccin/emacs#119]
# Problem
As of right now resizing fonts using `C-x -` will cause most of the text to resize, exception being emacs' builtin line-numbers. This causes line-height to remain the same when size is decreased.
# Solution
Poking around other themes, the fix for this issue seems to be to simply let the corresponding font faces to inherit from the default face.
## Note
On first sight it doesn't seem to change the style.
However since I do not use solaire or other plugins, which seem to also have line-number faces defined, I cannot say for sure.

**Comment by artemisYo** [comment]
This line specifically.
https://github.com/catppuccin/emacs/blob/7bd297677be5fbcffbbcbacbb1b47a0866b22339/catppuccin-theme.el#L322
Since it already defines a foreground and background color inheriting default shouldn't change anything.
The same applies to the aforementioned solaire face, however `ivy-grep-line-number` and `lsp-ui-peek-line-number` seem to not specify both, which I think could cause problems.

**Comment by artemisYo** [comment]
This should be all edits necessary
#120

**Comment by NamesCode** [comment]
I'll close this issue for now since the PR has been merged. If it arises again feel free to reopen :)
