### ISSUE TITLE
rustic quantize color error

### ISSUE THREAD

**Issue by uncomfyhalomacro** [catppuccin/emacs#121]
I just noticed this error when running `emacsclient`

```
Error (use-package): rustic/:catch: Symbol’s function definition is void: catppuccin-quantize-color
```

Not sure what that error even means so I will just leave this here as an issue.

**Comment by nyxkrage** [comment]
Do you only get this when using emacsclient?

**Comment by uncomfyhalomacro** [comment]
Seems so. I just checked `*Messages*`

**Comment by nyxkrage** [comment]
Hmm, I sadly wont be able to test this out myself until next week, feel free to ping me again then if I don't get back to this!

**Comment by artemisYo** [comment]
When I ran into the issue running any Catppuccin command seemed to fix this. So maybe this has something to do with the way the theme is loaded under the daemon?

**Comment by uncomfyhalomacro** [comment]
It seems so. `emacsclient`/`emacs daemon` is so weird. It sometimes loads packages incorrectly or incompletely. It's highly likely it's not even catppuccin-emacs issue

**Comment by uncomfyhalomacro** [comment]
Found a workaround. It seems it is an emacsclient behavior

```elisp
(add-hook 'server-after-make-frame-hook #'catppuccin-reload)
```

Not really a fix. but it works :) I think there is nothing to resolve this because it's a daemon behavior even I won't understand. So closing as WONT FIX since it is not yours to fix 🫡
