### ISSUE TITLE
`org-html-htmlize-generate-css` fails

### ISSUE THREAD

**Issue by nm3000a** [catppuccin/emacs#123]
Thank you for creating the latte theme.

I am generating the html version of an org-file. 
The command org-html-htmlize-generate-css fails with the following message
```
Invalid-face: markdown-blockquote-face 
```
I have tried changing the theme to leuven and it generates the css in a new buffer.

Catppuccin theme is the latest version.
Using it like this:
```
(use-package catppuccin-theme
  :ensure t)
(setq catppuccin-flavor 'latte)
(catppuccin-reload)
```
Emacs version: 30.0.50
org-mode: 9.6.9

Again, Thank you for your help.

**Comment by NamesCode** [comment]
I'll take a look later :3
