### ISSUE TITLE
Search results are not highlighted

### ISSUE THREAD

**Issue by edvin** [catppuccin/emacs#125]
After installing the catppuccin theme in spacemacs, it is impossible to distinguish the highlighted choice in certain scenarios, like for example by searching for a command with M-x. In the attached picture, choice no 4 is selected, and I suppose the background color should have changed to indicate that. I've tried changing every exposed color in the mocha palette, but none of the options seem to affect the choice highlight.

![image](https://github.com/catppuccin/emacs/assets/977035/bdebec4c-2ee5-40b8-a72a-ce68815deea3)

Compare to the default theme, there you can easily see the highlighted choice:

![image](https://github.com/catppuccin/emacs/assets/977035/f7ce04c0-ac27-4325-a881-54d67b7ad157)

**Comment by NamesCode** [comment]
huh, I think we're missing some faces here. I'll check it out later this week, just need to fix my emacs install.

**Comment by WhoisDonlee** [comment]
I'm not familiar with spacemacs, but to me it looks like catppuccin isn't loaded at all. Spacemacs probably has it's own way for setting a theme. Are you sure catppuccin is properly set?

**Comment by edvin** [comment]
Perhaps I'm doing it wrong, but I do see the colors. I configured this:

```lisp
dotspacemacs-additional-packages '(catppuccin-theme)
dotspacemacs-themes '(catppuccin)
```

**Comment by WhoisDonlee** [comment]
Are any of the faces displaying catppuccin colors? Either the theme is not set properly or something else is overriding the faces. Maybe try setting it interactively with load-theme and see if it displays the right colors.

**Comment by edvin** [comment]
Interesting - when I load the theme manually using `load-theme` I get this:

<img width="552" alt="image" src="https://github.com/catppuccin/emacs/assets/977035/e8fb1515-4580-4c37-8826-b7b521ca2993">

The colors (presumably) missing from the catppuccin theme is then the colors from the previous theme (doom-palenight, see the lime green text for example?). It really looks like there are some faces missing from the theme definition. I will try with a minimal config/without spacemacs layers asap to verify if it is some configuration of spacemacs that interferes.

**Comment by edvin** [comment]
I have confirmed that it's not a spacemacs issue. This is a screenshot taken with a minimal emacs config:

<img width="618" alt="image" src="https://github.com/catppuccin/emacs/assets/977035/0ce3c336-6016-4c07-9146-8aa75cbe4c82">

The highlight background color etc is still missing. For completeness/reproducibility, this is the complete `init.el`:

```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'catppuccin-theme)
(load-theme 'catppuccin :no-confirm)

(straight-use-package 'helm)
(global-set-key (kbd "M-x") 'helm-M-x)
```

It just loads `straight.el`, `catppucin-theme` and `helm` just to see the missing colors easily.

**Comment by edvin** [comment]
Perfect, thank you :)
