### ISSUE TITLE
Slow loading times

### ISSUE THREAD

**Issue by Orest58008** [catppuccin/emacs#127]
The theme is really slow to load/enable.
It takes almost twice as much to enable as Zenburn and what feels like thrice as much to take to usable GUI.
Elpaca, straight and package.el all produce roughly the same times, so they're not issue. What may be the issue and how can I attempt to fix it?

**Comment by NamesCode** [comment]
I'm unsure what could be leading to this. It could be that our theme uses some internal functions during the loading process, but if thats the case then we'd have to find a way to improve speed without deleting those functions.

Fell free to play around with it tho, if you do manage feel free to open a PR ^^

**Comment by rafagil** [comment]
@NamesCode I did a small bit of research on this and I figured the file is not being byte compiled. That leads to the veeeeeery slow loading times. If we remove the `no-byte-compile: t` flag in the beginning of the file, it loads as quickly as all other themes.
But, maybe that flag is there for a reason? If it was just an oversight, removing it improves the performance by a lot.

**Comment by NamesCode** [comment]
I'll see about testing it tomorrow, I don't see why we need to keep no-byte-compile so it should be safe to remove ^^

**Comment by NamesCode** [comment]
@Orest58008 Can you test with the new version of the theme?

**Comment by Orest58008** [comment]
Unfortunately I can't because I've moved to Neovim due to some weird issues with fonts in GNU Emacs itself

**Comment by NamesCode** [comment]
Ah ok, it should be fine regardless ^^. Hope you enjoy Neovim, i've made the switch too
