### ISSUE TITLE
Font in example screenshot

### ISSUE THREAD

**Issue by jthorpe6** [catppuccin/emacs#130]
Hi,

What is the font used in the example screenshot ?

Thanks

**Comment by nyxkrage** [comment]
It's my build of Recursive Mono, the config can be found here https://github.com/nyxkrage/sanctureplicum-nur/blob/main/pkgs/rec-mono-nyx/default.nix#L13-L61 and instructions for how to build a custom recursive config can be found here https://github.com/arrowtype/recursive-code-config?tab=readme-ov-file#usage
