### ISSUE TITLE
Failed to set catppuccin flavor `Symbol's function definition is void: catppuccin-reload`

### ISSUE THREAD

**Issue by asob** [catppuccin/emacs#131]
My `init.el` looks like this

```lisp
(load-theme 'catppuccin t )
(setq catppuccin-flavor 'latte)
(catppuccin-reload)
```

The following error appears after reloading config: `Symbol's function definition is void: catppuccin-reload`

If `catppuccin-reload` is omitted the theme loads but with default flavor.

**Comment by NamesCode** [comment]
Which version of emacs are you using?

**Comment by asob** [comment]
`GNU Emacs 29.1 (build 2, x86_64-w64-mingw32)`

Executing the config below doesn't work either

```lisp
(load-theme 'catppuccin t )
(setq catppuccin-flavor 'latte)
(disable-theme 'catppuccin)
(load-theme 'catppuccin t)
```

**Comment by NamesCode** [comment]
Oh dear, I'll have to look into this. Are you able to enable the theme at all?

**Comment by asob** [comment]
> Oh dear, I'll have to look into this. Are you able to enable the theme at all?

Yes, theme gets enable, just not possible to switch flavor.

**Comment by h4rr9** [comment]
Facing same issue, but am able to switch to latte by calling `catppuccin-load-flavor` interactively.

running doom on emacs 29.1.

**Comment by MoritzHamann** [comment]
emacs 29.1, facing the same issue. using

```
(use-package catppuccin-theme
  :ensure t
  :demand
  :config
  (load-theme 'catppuccin t)
  (catppuccin-load-flavor 'macchiato))
```

gives me the default theme, but throws the following error:

```
Error (use-package): catppuccin-theme/:config: Symbol’s function definition is void: catppuccin-load-flavor
```

It looks like none of the `catppuccin-*` functions can be called interactively as well

**Comment by MoritzHamann** [comment]
I'm relatively new to the emacs ecosystem and I'm not sure if it's relevant, but the downloaded `catppuccin-theme-pkg.el` file references a commit from Oct 2022:

```
(define-package "catppuccin-theme" "0.1.0" "Catppuccin Theme"
  '((emacs "25.1"))
  :commit "f36765cbbd4129aabb22250a87e90a1387bd5dc7" :authors
  '(("pspiagicw"))
  :maintainers
  '(("pspiagicw" . "pspiagicw@gmail.com"))
  :maintainer
  '("pspiagicw" . "pspiagicw@gmail.com")
  :url "https://github.com/catppuccin/emacs")
;; Local Variables:
;; no-byte-compile: t
;; End:
```

**Comment by MoritzHamann** [comment]
For anyone reading this in the future: my issue was installing the package from `melpa-stable` rather than `melpa`, which resulted in the outdated package. after reinstalling from melpa everything worked.

**Comment by drishal** [comment]
> For anyone reading this in the future: my issue was installing the package from `melpa-stable` rather than `melpa`, which resulted in the outdated package. after reinstalling from melpa everything worked.

may I please know how did you switch the package from melpa-stable to melpa using elpaca?

**Comment by MoritzHamann** [comment]
> > For anyone reading this in the future: my issue was installing the package from `melpa-stable` rather than `melpa`, which resulted in the outdated package. after reinstalling from melpa everything worked.
> 
> may I please know how did you switch the package from melpa-stable to melpa using elpaca?

not sure how to do it with elpaca, I'm using `use-package`. For that I've just added this to the front of my `init.el`:

```
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
```

**Comment by NamesCode** [comment]
> For anyone reading this in the future: my issue was installing the package from `melpa-stable` rather than `melpa`, which resulted in the outdated package. after reinstalling from melpa everything worked.

Ah nice, Thank you for explaining what went wrong <3
