### ISSUE TITLE
rustic issue

### ISSUE THREAD

**Issue by drishal** [catppuccin/emacs#140]
in the logs I am getting the issue ` rustic/:catch: Symbol’s function definition is void: catppuccin-quantize-color`, because of which rustic mode cannot be started and the colors in rust-mode are not correctly applied
Can this problem please be fixed? 
```
 emacs --version
GNU Emacs 30.0.50
```
using elpaca with the configuration 
```lisp
(use-package catppuccin-theme
  :demand t
  :config
  (load-theme 'catppuccin t)
  (catppuccin-load-flavor 'macchiato)
  (catppuccin-reload))
```

**Comment by nyxkrage** [comment]
Sadly I haven't been able to figure out why specifically rustic, catppuccin-emacs and emacsclient are having problems, so until someone can figure it out and point towards where the fix would be to use the workaround in https://github.com/catppuccin/emacs/issues/121#issuecomment-1689819343
