### ISSUE TITLE
Add support for Helm

### ISSUE THREAD

**Issue by lunacd** [catppuccin/emacs#143]
#125 touches upon this, and we already have an unimplemented section here: https://github.com/catppuccin/emacs/blob/3d93abaa33e95f19b4a8b0e1e9bef1e3e68dd994/catppuccin-theme.el#L628-L657 

It'd be nice to have helm supported. And if someone can point me to how I could approach this, I can take a stab at it as well.

**Comment by NamesCode** [comment]
> #125 touches upon this, and we already have an unimplemented section here:
> 
> https://github.com/catppuccin/emacs/blob/3d93abaa33e95f19b4a8b0e1e9bef1e3e68dd994/catppuccin-theme.el#L628-L657
> 
> It'd be nice to have helm supported. And if someone can point me to how I could approach this, I can take a stab at it as well.

Heyo! if you want to take a go at it i'm free to have a call on discord at any point to explain things, otherwise I can get around to doing this at some point

**Comment by lunacd** [comment]
> Heyo! if you want to take a go at it i'm free to have a call on discord at any point to explain things, otherwise I can get around to doing this at some point

Thanks for reaching out! Unfortunately or fortunately, I have been exclusively using Ivy with issues lol. Maybe I'll take a stab at this when I feel the need to switch to Helm :)

**Comment by NamesCode** [comment]
All good! ^^
