### ISSUE TITLE
eglot company mode icons illegible due to background color 

### ISSUE THREAD

**Issue by drishal** [catppuccin/emacs#149]
The current company mode icons are illegible with the selected color in company mode
![image](https://github.com/catppuccin/emacs/assets/32875739/c817f069-49d1-4486-915f-e71b7d2609ed)

suggested color: use the same highlighted background color  as neovim 
![image](https://github.com/catppuccin/emacs/assets/32875739/69026ba3-51e9-465c-b0be-bcd5e770d5e8)

**Comment by NamesCode** [comment]
Heyo! I've fixed this in the pr #152

**Comment by NamesCode** [comment]
Wrong button
