### ISSUE TITLE
Error when installed with Doom Emacs using package.el

### ISSUE THREAD

**Issue by henrychea** [catppuccin/emacs#15]
```
x There was an unexpected runtime error
      Message: Error with packages
      Details: ("catppuccin-theme" (error "catppuccin-macchiato-theme.el:0:0: error: scan-error: (Unbalanced parentheses 205 27640)"))
      Backtrace:
        (signal doom-package-error ("catppuccin-theme" (error "catppuccin-ma...
        (condition-case e (let ((straight-use-package-pre-build-functions (c...
        (progn (if (file-directory-p (straight--repos-dir local-repo)) nil (...
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (...
        (cl-destructuring-bind (&key recipe package type local-repo &allow-o...
        (straight--with-plist (append (list :recipe recipe) recipe) (recipe ...
        (let ((recipe (car --dolist-tail--))) (straight--with-plist (append ...
        (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straig...
        (let ((--dolist-tail-- recipes)) (while --dolist-tail-- (let ((recip...
        (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-us...
        (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (stra...
        (let* ((built (and t (let* ((recipes (doom-package-recipe-list)) (bu...
      ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.221011163423.58523.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
```

[cli.doom.221011163423.58523.log](https://github.com/catppuccin/emacs/files/9753691/cli.doom.221011163423.58523.log)

**Comment by henrychea** [comment]
Installed with `(package! catppuccin-theme)`

**Comment by NamesCode** [comment]
Currently not on melpa, you will have to download locally for now. I will notify you once it is on melpa.

**Comment by henrychea** [comment]
> Currently not on melpa, you will have to download locally for now. I will notify you once it is on melpa.

Thanks!

**Comment by Occhioverde** [comment]
In case it can be useful, you can insert the following snippet in your `packages.el` file in order to automatically download Catppuccin:

```elisp
; Install Catppuccin theme
; Dependencies: Autothemer
(package! autothemer)
; Theme package
(package! catppuccin
  :recipe (:host github :repo "catppuccin/emacs"))
```

**Comment by NamesCode** [comment]
Waiting for melpa to approve new package recipe

**Comment by dhruvinsh** [comment]
melpa has it now. https://melpa.org/#/?q=catppuccin

**Comment by NamesCode** [comment]
> melpa has it now. https://melpa.org/#/?q=catppuccin

Sadly not yet, That would be the older version.

**Comment by dhruvinsh** [comment]
According to melpa the version is 	
20221023.2331, am I missing something?

**Comment by ignamartinoli** [comment]
Installing with `M-x package-list-packages` works, but not with `use-package`

**Comment by nekowinston** [comment]
Whats the progress on this @NamesCode?

**Comment by ignamartinoli** [comment]
@nekowinston I just tried installing it from Melpa and it's not working

**Comment by nyxkrage** [comment]
@ignamartinoli I can't seem to reproduce any issues with plain Emacs or with Doom Emacs
`(package-install 'catppuccin-theme)` for regular Emacs and `(package! catppuccin-theme)` in packages.el for Doom
and then followed by loading it like you usually would with either `load-theme` or `setq doom-theme`

**Comment by NamesCode** [comment]
> Whats the progress on this @NamesCode?

Currently gonna replace the melpa repo with this and then continue the process. I paused due too many changes in the repo and melpa is slow to upgrade

**Comment by NamesCode** [comment]
> @nekowinston I just tried installing it from Melpa and it's not working

Its currently not on melpa

**Comment by nyxkrage** [comment]
Ignore @NamesCode, the latest commit d352e8 is the one that currently on Melpa

**Comment by ignamartinoli** [comment]
Just deleted the `elpa` folder to force a clean update. Now it works perfectly with

```
(use-package catppuccin-theme
  :config (load-theme 'catppuccin t)
  :init (setq catppuccin-flavor 'macchiato))
```

it also gets installed automatically from ELPA/MELPA I think
