### ISSUE TITLE
Unable to find theme file for 'catppuccin-theme'

### ISSUE THREAD

**Issue by Andr3wcr0z** [catppuccin/emacs#151]
Every time I try launching Doom Emacs I get this message saying: "*ERROR*: Unable to find theme file for 'catppuccin-theme'" I installed the theme the way that the README says for Doom Emacs. I have tried uninstalling and installing the package, and still nothing.

**Comment by NamesCode** [comment]
![wisdom_of_the_ancients.png](https://github.com/catppuccin/emacs/assets/86119896/ba55ec04-bc42-48ce-9eba-e8056cee55b7)

**Comment by Andr3wcr0z** [comment]
also, I just simply killed the doom emacs server and emacsclient and restarted emacs :+1:

**Comment by NamesCode** [comment]
ah nice lmao. Soz for the meme, I just like posting xkcd when I can 😅
