### ISSUE TITLE
variables are not blue  

### ISSUE THREAD

**Issue by drishal** [catppuccin/emacs#153]
Vscode:
![image](https://github.com/catppuccin/emacs/assets/32875739/cd7d581a-dfe0-44e8-9c61-bbc3295beff1)
Emacs:
![image](https://github.com/catppuccin/emacs/assets/32875739/5fbaa911-a4e5-4cd8-95ff-44f262fea658)

**Comment by jtbx** [comment]
This is a problem with your major mode, nix-mode if I'm correct. Try installing `nix-ts-mode` and see if that makes a difference.
