### ISSUE TITLE
Support word granularity git diffs

### ISSUE THREAD

**Issue by zrquan** [catppuccin/emacs#154]
In dracula theme:

![Screenshot_20240704_140857](https://github.com/catppuccin/emacs/assets/33086594/fc58c68f-094b-4b9a-86a6-b0b2746fe455)

Switch to catppuccin theme:

![Screenshot_20240704_140841](https://github.com/catppuccin/emacs/assets/33086594/0d0705ee-b0c9-45a2-94b8-c9800fdf45cc)

**Comment by jtbx** [comment]
What face is magit using to display that line diff? If you don't know just move your cursor over one of those highlighted changes in the dracula theme and press M-x `describe-char`, then it'll tell you the face it's using for that character.

**Comment by zrquan** [comment]
> What face is magit using to display that line diff?

diff-refine-added and diff-refine-removed

**Comment by jtbx** [comment]
Weird, those faces aren't used in my magit. Do you have any special setup at all?

I was experimenting around with trying to support this in #158 (using diff-refine- faces) but I could only see a difference in diff-mode. If your magit uses those faces for some reason then #155 should work as a fix for you, but it would be awesome if you could try those changes out yourself and tell me if it made a difference. Currently I'm still experimenting with the colours on that PR, nothing's final yet.

**Comment by zrquan** [comment]
> Weird, those faces aren't used in my magit. Do you have any special setup at all?

I haven't set up magit myself, but I'm using Doom Emacs, so that might be the reason. 🤔

> but it would be awesome if you could try those changes out yourself and let me know about it

I tried the changes in #158, and they worked for me. However, the foreground color can be adjusted to make the text stand out better.

![image](https://github.com/user-attachments/assets/51d84a34-cddb-4bd1-8788-2955aa873082)

**Comment by jtbx** [comment]
Thank you!
