### ISSUE TITLE
NEW MAINTAINER WANTED 

### ISSUE THREAD

**Issue by NamesCode** [catppuccin/emacs#155]
I, unfortunatly, don't have the time to work on this anymore.

If anyone would like to take the mantle of this repo, please reply to to this issue. Joining the discord server and discussing your interest there will make application faster.

Thank you in advance.

**Comment by jtbx** [comment]
I'd be up for maintaining the theme if you're still looking for someone to take over.

**Comment by NamesCode** [comment]
Should pass you maintainership soon ^^
