### ISSUE TITLE
Wrong background color in Centaur tabs bar

### ISSUE THREAD

**Issue by Occhioverde** [catppuccin/emacs#17]
As you can see in the following image, the Centaur tabs bar's background is white even though I loaded the Catppuccin Mocha theme:

![Wrong Centaur tabs bar background](https://user-images.githubusercontent.com/18429412/195853015-6bc00141-83a7-46b3-b11f-30efe3b82877.png)

When using Doom One the bar's background is the same as other buffers, while this is not the case with Catppuccin Mocha.

I am totally ignorant about Emacs themes, so mine is only an hypothesis, but maybe there is a buffer type that is not correctly themed by Catppuccin.

**Comment by NamesCode** [comment]
I'm unsure if the theme even supports centaur tabs but I can take a look

**Comment by ignamartinoli** [comment]
Just came to report this and saw it's already open

**Comment by ignamartinoli** [comment]
This issue appears to be solved for me
