### ISSUE TITLE
diff-hl indicators not shown in fringe

### ISSUE THREAD

**Issue by gekoke** [catppuccin/emacs#185]
With catppuccin-theme (`mocha` variant):

![image](https://github.com/user-attachments/assets/d558d614-4bb3-44ec-b7f3-563d075398b2)

WIth modus-vivendi:

![image](https://github.com/user-attachments/assets/d5343bca-9dff-4b03-aabe-2fc462ea3e74)

**Comment by jtbx** [comment]
I've made #186, would you be able to test that out? On my Emacs I can at least see a thin border around the gutter indicators but that should set a concrete colour for the whole thing.

**Comment by gekoke** [comment]
Yes, that works for me - looks the same as in the images attached to the PR.

**Comment by jtbx** [comment]
Neat, thanks!
