### ISSUE TITLE
rustic and eglot failure with catppuccin theme

### ISSUE THREAD

**Issue by drishal** [catppuccin/emacs#187]
this particular error:  rustic/:catch: Symbol’s function definition is void: catppuccin-quantize-color is causing issues with eglot on rustic mode to fail, and instead tries to install lsp-mode, but this happens only in emacsclient.
Howerver this works fine if emacs is started as a separate instance and rustic starts up eglot correctly 
```lisp
(use-package catppuccin-theme
  :demand t
  :init
  (setq catppuccin-flavor 'mocha) ;; or 'latte, 'macchiato, or 'mocha
  (load-theme 'catppuccin)
  (add-hook 'server-after-make-frame-hook #'catppuccin-reload)
  )
(use-package rust-mode
  :demand t
  :init
  (setq rust-mode-treesitter-derive t))

(use-package rustic
  :after (rust-mode)
  :demand t
  :config
  (setq lsp-enable-symbol-highlighting nil)
  (setq lsp-signature-auto-activate nil)
  ;; eglot mode
  (setq rustic-lsp-client 'eglot)
  )
  ```

**Comment by jtbx** [comment]
That's really weird it's not working in emacsclient. The problem is that some library is trying to call an internal theme function (`catppuccin-quantize-color`), and this function is unbound at the end of the theme.

https://github.com/catppuccin/emacs/blob/fe83fa19fad9d39b9921ae84dd974e0806ebf18a/catppuccin-theme.el#L1519

I've opened #188 to remove these calls, would you be able to test out that branch and let me know if that works for you?

**Comment by drishal** [comment]
> That's really weird it's not working in emacsclient. The problem is that some library is trying to call an internal theme function (`catppuccin-quantize-color`), and this function is unbound at the end of the theme.
> 
> https://github.com/catppuccin/emacs/blob/fe83fa19fad9d39b9921ae84dd974e0806ebf18a/catppuccin-theme.el#L1519
> 
> I've opened #188 to remove these calls, would you be able to test out that branch and let me know if that works for you?
Hopefully if I am pulling down the package correctly
```lisp
(use-package catppuccin-theme                                                                                                                                                      
	     :ensure (:host github :repo "catppuccin/emacs" :branch "internal")                                                                                                               
	     :init                                                                                                                                                                            
	     (setq catppuccin-flavor 'mocha) ;; or 'latte, 'macchiato, or 'mocha                                                                                                              
	     (load-theme 'catppuccin)                                                                                                                                                         
	     (add-hook 'server-after-make-frame-hook #'catppuccin-reload)                                                                                                                     
	     )  
 ```
 the error message seems to be resolved and eglot is called properly

**Comment by jtbx** [comment]
Awesome thanks. :heart:
