### ISSUE TITLE
Better color support for lsp-mode headerline

### ISSUE THREAD

**Issue by Tired-Fox** [catppuccin/emacs#19]
I noticed that parts of the bar in lsp-mode headerline have a dark background when I would assume it would be the base color.
![image](https://user-images.githubusercontent.com/94603332/196068278-f640870f-1e13-45a1-bf2c-3c81267dc493.png)
![image](https://user-images.githubusercontent.com/94603332/196068296-81a676d1-b050-4058-805c-62154db09a8e.png)

According to the [LSP Mode > Headerline documentation](https://emacs-lsp.github.io/lsp-mode/page/settings/headerline/#lsp-headerline-breadcrumb-path-face) most of the components inherit from `font-lock-string-face`

Not sure what it would be pulling from to get the non-base color for background.

**Comment by Askath** [comment]
Added new PR.
I set the background for various elements in the breadcrumbs to base. Have not seen any further issues with it while testing different filetypes and paths.

If somethings of let me know

**Comment by NamesCode** [comment]
👍

**Comment by Manueljlin** [comment]
I'm pretty new to Emacs, so I'm sorry if I'm missing something obvious, but I'm still seeing the issue:
![Screen Shot 2022-12-20 at 15 10 33](https://user-images.githubusercontent.com/11275573/208686488-7055aeb1-d275-417b-a462-13a5cf836fdd.png)
![Screen Shot 2022-12-20 at 15 11 48](https://user-images.githubusercontent.com/11275573/208686700-ef0e8cb1-e8c3-4990-9361-2c9372d29311.png)
This is my config: https://gitlab.com/manueljlin/emacs-config/-/blob/main/init.el#L324

**Comment by Manueljlin** [comment]
alright, nevermind. I'm just dumb and didn't notice the fix didn't land on the main branch yet. sorry for the noise
