### ISSUE TITLE
Missing catppuccin-definitions.el in ~/.emacs.d

### ISSUE THREAD

**Issue by jeremie2** [catppuccin/emacs#191]
- **Ubuntu 24.04**
- **Emacs 29.3** via apt package
- Config file: `~/.emacs.d/init.el`
- **MELPA** repo

Hi, just started using Emacs (not really expert!) and couldn't find a way to make Catppuccin theme work till I noticed an Emacs message about a missing _definitions.el_ file in the `.emacs.d` directory.
I've copied  `~/.emacs.d/elpa/catppuccin-theme-20240829.2151/definitions.el` into `~/.emacs.d` and everything started to work as expected 🎉

As already written I'm not expert and I don't know if that file is supposed to be automatically copied into `.emacs.d` or not, if this situation happens only with the combination of operating system and software on my computer.
Anyway, if coping that file is an expected step for the Catppuccin configuration, then it could be add to the [README.md](https://github.com/catppuccin/emacs/blob/main/README.md) file.

Cheers!

**Comment by jeremie2** [comment]
> That's weird, it should be looking for catppuccin-definitions.el.

OK that was enough to believe that while trying to get things working I must have  screwed up the normal configuration.
I went through a clean installation, followed the step in [README.md](https://github.com/catppuccin/emacs/blob/main/README.md) and Catppuccin theme works perfectly.

 I'm very sorry for the false alarm! But thank you very much for the prompt answer!

**Comment by jtbx** [comment]
No worries feel free to open a new issue if you have any more problems.
