### ISSUE TITLE
LaTeX mode not following the palette?

### ISSUE THREAD

**Issue by ghost** [catppuccin/emacs#2]
As you can see in my screenshot, the _red_ of the double backslash is a bit too bright, and it stands out a lot,  this color doesn't exist in the catppuccin palette, is this intentional? 

![Screenshot from 2022-04-16 16-12-38](https://user-images.githubusercontent.com/56168664/163676813-d6e3a9e6-442b-47ea-9d6a-a360a10e8f82.png)

**Comment by pspiagicw** [comment]
I can't reproduce this. I am getting this. Can you described how did you load this theme ? It can be that some effect of previous theme is affecting the current theme.

![Screenshot from 2022-04-25 23-08-41](https://user-images.githubusercontent.com/30765406/165143540-96b142eb-670a-4c04-bb71-068cbe4f546f.png)

**Comment by jwijenbergh** [comment]
> I can't reproduce this. I am getting this. Can you describe how did you load this theme ? It can be that some effect of a previously applied theme is affecting the current theme.
> 
> ![Screenshot from 2022-04-25 23-08-41](https://user-images.githubusercontent.com/30765406/165143540-96b142eb-670a-4c04-bb71-068cbe4f546f.png)

You have a } after the \Large, thus not reproducing the error color

**Comment by NamesCode** [comment]
Updated [colour palette](https://github.com/catppuccin/emacs/commit/765293325d91abe891335b55ad8c3ea3dd4b471b) so I am unsure if this is still an issue. If it is I will reopen issue.
