### ISSUE TITLE
Properties having weird background color

### ISSUE THREAD

**Issue by svnsbck** [catppuccin/emacs#20]
Hi! 
Great job on the themes, like them a lot.  I ran though into some minor issues with :PROPERTIES: in an org-document.  They all have some likely unintented background. This is in in all variants except when loading only the 'cattpuccin theme.
![20221019T093413--selection__screenshot](https://user-images.githubusercontent.com/8381669/196615069-8602c2a6-c431-44e6-91ed-b04e2f6c8759.jpg)

Can I fix this myself somehow?

**Comment by NamesCode** [comment]
Someone need set Surface1 <img src="https://github.com/catppuccin/catppuccin/blob/main/assets/palette/circles/mocha_surface1.png" height="23" width="23"/> as the background for that. I will look into it to either do it myself or put up info on how to.

**Comment by Askath** [comment]
Hello,
I was looking at this issue as my first contribution. I think I found the according setting, although it is already set as surface1 which results in the background shown.

 What color is supposed to be there? or should there be no colored background for the meta information at all?
 
<img width="885" alt="Bildschirm­foto 2022-11-18 um 21 08 04" src="https://user-images.githubusercontent.com/42957914/202793444-4d79a2f2-2932-40d6-ab56-078d187e4aea.png">

**Comment by Askath** [comment]
Is that how it is supposed to be?

<img width="526" alt="Bildschirm­foto 2022-11-20 um 20 04 40" src="https://user-images.githubusercontent.com/42957914/202920876-45694cdd-6220-4721-be38-e54b1e9705d4.png">

**Comment by svnsbck** [comment]
It does look good to me :-)

**Comment by Askath** [comment]
okay, I'll add a PR for this later :)

**Comment by Askath** [comment]
Added pull request that replaces the coloring to the base colour
