### ISSUE TITLE
Macchiato unsupports dashboard colored icons

### ISSUE THREAD

**Issue by ignamartinoli** [catppuccin/emacs#24]
When on `dashboard`, if the _Macchiato_ flavor is selected, all icons from `all-the-icons` become grey like this
![20221110124942](https://user-images.githubusercontent.com/103866722/201141313-e164c740-4843-4b62-b7fe-f9e27d6531c9.png)

The meaningful configuration is as follow

```elisp
(use-package dashboard
  :config (progn (dashboard-setup-startup-hook)
                 (setq dashboard-set-file-icons t
                       dashboard-set-heading-icons t)))
(use-package all-the-icons
  :if (display-graphic-p))

(use-package catppuccin-theme
  :config (load-theme 'catppuccin-macchiato t)
  :ensure autothemer)
```

`centaur-tabs` icons are unaffected. Also the issue is not present on _Mocha_ as you can see

![20221110125245](https://user-images.githubusercontent.com/103866722/201142145-e3b86e44-218b-4fba-a233-3deb20ebfea7.png)

**Comment by nekowinston** [comment]
Is this still an issue after merging #42?

**Comment by ignamartinoli** [comment]
Solved!
