### ISSUE TITLE
No bold in emacs?

### ISSUE THREAD

**Issue by JxJxxJxJ** [catppuccin/emacs#28]
Normal text seems to be bold as default 
![image](https://user-images.githubusercontent.com/103049321/203458180-69fe3971-6927-4064-a0f1-c7a478574674.png)

**Comment by nekowinston** [comment]
Possibly - I'm personally not really familiar with emacs. It could depend on your terminal emulator?

Better to ask the emacs maintainer. 🙂 @NamesCode

**Comment by JxJxxJxJ** [comment]
Oh no problem, and I'm using it as a GUI. If I find something I'll write here.

**Comment by JxJxxJxJ** [comment]
It was the font :) changing to monospace:h17 solved it :+1: 
![image](https://user-images.githubusercontent.com/103049321/203462232-ea16284f-9fa8-468c-a9d4-8a0af7b1111f.png)

**Comment by nekowinston** [comment]
Glad you could solve it, I'll close this then.
