### ISSUE TITLE
Weird colors near indentations and code blocks

### ISSUE THREAD

**Issue by JxJxxJxJ** [catppuccin/emacs#30]
This 'lighter' color populates zones that are a little weird ![image](https://user-images.githubusercontent.com/103049321/203629447-009edde5-b225-40ef-8bd2-f57bdf3a9b6c.png)

**Comment by JxJxxJxJ** [comment]
The codeblocks are still 'blocks' and the indentation isn't colored differently than the background

**Comment by YaN-3k** [comment]
There is similar issue in `ansi-term` but the blocks are darker.
![image](https://user-images.githubusercontent.com/54375296/203632579-fbdf9a86-520f-46e4-957f-76b33c227481.png)

**Comment by Askath** [comment]
Also similar issue when using a plugin like focus.
![grafik](https://user-images.githubusercontent.com/42957914/203805255-c43e6b5b-3028-4adb-92c1-2186924f142f.png)


I might take a look on this later, kinda annoys me :D
