### ISSUE TITLE
Sync the dev and main branches

### ISSUE THREAD

**Issue by Manueljlin** [catppuccin/emacs#35]
Currently, there's a few changes that are exclusive to each branch, like lsp-mode breadcrumbs in the dev branch and dired+magit only in the main branch.

Basically, the two branches have now diverged and should be rebased against each other.

**Comment by NamesCode** [comment]
I will get to this in a few minutes. also merry christmas :)

**Comment by NamesCode** [comment]
Hopefully this has been completed correctly :)
