### ISSUE TITLE
Doom-Emacs: "Symbol's variable is void: catppuccin-bg"

### ISSUE THREAD

**Issue by Kovalentus** [catppuccin/emacs#47]
Issue:

> Symbol's variable is void: catppuccin-bg

Commenting line 853 and 855 of catppuccin-theme.el fixes the issue but introduces error

> Symbol's variable is void: bg2

Commenting line 854 fixes the issue and theme loads

**Comment by backwardspy** [comment]
hey, thanks for raising this! it should be fixed now.

**Comment by Kovalentus** [comment]
Yep, logged out to my other account on the computer to verify if I could reproduce the error on a Doom install with default configs, but after running Doom sync I couldn't reproduce the issue - felt a bit foolish at first until I doublechecked and saw it was already fixed lol

So verified as working
