### ISSUE TITLE
Org checked item shaded

### ISSUE THREAD

**Issue by ignamartinoli** [catppuccin/emacs#49]
It would be nice to see checked Org list items as shaded.

(Also, colored square brackets for the list check-space)

An example from `doom-theme`:

![20230113012245](https://user-images.githubusercontent.com/103866722/212242508-44dec5c3-407f-42cf-a450-49663984c0f7.png)

**Comment by ignamartinoli** [comment]
@nyxkrage I've been trying to make it work.

Between checking into other themes and testing I'm quite sure it's the `org-headline-done` face that has to be set. But for some reason the changes I apply to it aren't shown.

I'm not really sure why

**Comment by nyxkrage** [comment]
Hey @ignamartinoli I couldn't seem replicate the fact that the headline wasn't shaded on my machine, but I've pushed up a small fix that should change the color of the brackets and unifies the brackets/checkbox and the title of the headline to match what other themes are doing.
Can you check if this is still a problem, and if so reopen the issue and send a screenshot of what it looks like with the catppuccin theme
