### ISSUE TITLE
Catppuccin 0.2.0

### ISSUE THREAD

**Issue by Elijah-29** [catppuccin/emacs#5]
Catppuccin Version 2

![image](https://user-images.githubusercontent.com/102277445/171603781-75d3ff12-01a1-4910-9175-e3eec14e4b7c.png)

hope the best theme can update for emacs

**Comment by pspiagicw** [comment]
In Progress checkout the `catppuccin-2` branch

**Comment by azerbe** [comment]
Hey, that branch is not available 😢

**Comment by fbergroth** [comment]
Perhaps v2 can be implemented as a derivative of modus-themes by specifying overrides for each palette. See https://protesilaos.com/codelog/2022-07-26-modus-themes-color-override-demo/

**Comment by pspiagicw** [comment]
Sorry for the lack of response. I was busy with college work. I am planning to add the themes within a week or so. Stay tuned! If anybody wants to contribute don't hesitate.

**Comment by NamesCode** [comment]
Ported over to V2.0, Checkout the pull request
