### ISSUE TITLE
Yaml file isn't highlighted properly.

### ISSUE THREAD

**Issue by Pacane** [catppuccin/emacs#55]
Not sure why, but when using this theme (whatever variant), Yaml syntax highlight isn't working that well.

![image](https://user-images.githubusercontent.com/2762440/213926839-44aa26f6-3b9b-463a-aa67-62573475d407.png)

See for comparison doom-one

![image](https://user-images.githubusercontent.com/2762440/213926861-91527f85-0734-425d-a033-a82efdb08175.png)

**Comment by nyxkrage** [comment]
Hey, yeah this is mainly an issue with Emacs' YAML support, as the keys are bound to the regular font-lock variable face, as a workaround you can use this snippet
```lisp
(add-hook 'yaml-mode-hook
  (lambda ()
    (face-remap-add-relative 'font-lock-variable-name-face
                                            (list :foreground (catpuccin-get-color 'blue)))))
``

**Comment by Pacane** [comment]
That works! Thanks. Just a typo for the reference though, the function is actually `catppuccin-get-color`
