### ISSUE TITLE
Different Coloured headings in Org mode?

### ISSUE THREAD

**Issue by Midnight1938** [catppuccin/emacs#56]
Most themes have coloured headings in org mode, wont it be possible to do the same for catppuccin?

## Example theme
![image](https://user-images.githubusercontent.com/58230351/216039312-ee5dd12c-c525-4e3e-93d6-43164a54f99a.png)

## Catppuccin
![image](https://user-images.githubusercontent.com/58230351/216039399-43bda103-b50a-4ef5-ad76-7b7955504868.png)

**Comment by nyxkrage** [comment]
It was originally done like this to stay in line with how JetBrains and Neovim treat headings, so perhaps this should be discussed as a org wide change for the rest of our editors, I am certainly open to having different colors.

**Comment by NamesCode** [comment]
If you want to change it for your editor open `catppuccin.el` and go to line `777` (M-g g 777) then select up to the end of line `790` (C-SPC, M-g g 790) then paste this
```org
               (org-level-1 :inherit bold :foreground ,ctp-blue
                            ,@(when catppuccin-enlarge-headings
                                (list :height catppuccin-height-title-1)))
               (org-level-2 :inherit bold :foreground ,ctp-red
                            ,@(when catppuccin-enlarge-headings
                                (list :height catppuccin-height-title-2)))
               (org-level-3 :weight normal :foreground ,ctp-green
                            ,@(when catppuccin-enlarge-headings
                                (list :height catppuccin-height-title-3)))
               (org-level-4 :weight normal :foreground ,ctp-lavender)
               (org-level-5 :weight normal :foreground ,ctp-yellow)
               (org-level-6 :weight normal :foreground ,ctp-maroon)
               (org-level-7 :weight normal :foreground ,ctp-teal)
               (org-level-8 :weight normal :foreground ,ctp-mauve)
```
Then save the file and reload the theme. It should look like this:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/86119896/216093225-7669a163-49ac-490b-bdf5-98a215fe0535.png">
