### ISSUE TITLE
Conflictions with theming of other packages

### ISSUE THREAD

**Issue by chookity-pokk** [catppuccin/emacs#57]
I am using line-reminder and the default value of a modified line was essentially invisible in the latte theme. I made a PR for them and they suggested to upstream it here. I'm not really sure how to go about it so I figured I'd just open an issue. 

Below is the PR from line-reminder. 

https://github.com/emacs-vs/line-reminder/pull/22

**Comment by NamesCode** [comment]
I will fix this. Thanks for bringing it up :)

**Comment by chookity-pokk** [comment]
Thank you! Do you mind if I ask how? I was digging through the code to see what would be done and I couldn't figure out anything other than changing the fringe color.

**Comment by chookity-pokk** [comment]
To add to this (didn't think opening another issue would make sense). There is also an issue with latte where the line-reminder with ts-folding shows up very duly making it hard to see. Switching to the frappe theme shows what it should look like. 

Latte:
![image](https://user-images.githubusercontent.com/24358100/216793581-e443a4af-6559-418c-b920-1ee57fd545bf.png)

Frappe:
![image](https://user-images.githubusercontent.com/24358100/216793588-b677e825-f0ae-4dbf-8a98-d029f3d6b88c.png)

**Comment by nyxkrage** [comment]
> Thank you! Do you mind if I ask how? I was digging through the code to see what would be done and I couldn't figure out anything other than changing the fringe color.
@chookity-pokk 

Yeah you would take a look at what faces `line-reminder` defines, I usually just search the repo for `defface`, but another option is using `M-x describe-face` then looking at any starting with `line-reminder`

After this is about adding them to the theme in the `faces '(...` part in the following format
```elisp
(face-name :foreground ,ctp-COLOR :background ,ctp-COLOR)
```

**Comment by NamesCode** [comment]
I normally just search for `faces.el` in any repo

**Comment by NamesCode** [comment]
> I am using line-reminder and the default value of a modified line was essentially invisible in the latte theme. I made a PR for them and they suggested to upstream it here. I'm not really sure how to go about it so I figured I'd just open an issue.
> 
> Below is the PR from line-reminder.
> 
> [emacs-vs/line-reminder#22](https://github.com/emacs-vs/line-reminder/pull/22)

I didn't use the exact HEX value as you did in your pr, is this fine?

**Comment by chookity-pokk** [comment]
If you think it looks fine then that's good enough for me! I ended up picking a mostly random number when I got mine.

**Comment by NamesCode** [comment]
> If you think it looks fine then that's good enough for me! I ended up picking a mostly random number when I got mine.

Great! If you want you can peer review the theme before I merge just to double check if it works correctly, otherwise I can merge the PR and close the issue now :).

**Comment by chookity-pokk** [comment]
> > If you think it looks fine then that's good enough for me! I ended up picking a mostly random number when I got mine.
> 
> Great! If you want you can peer review the theme before I merge just to double check if it works correctly, otherwise I can merge the PR and close the issue now :).

Looks good to me!

**Comment by NamesCode** [comment]
> > > If you think it looks fine then that's good enough for me! I ended up picking a mostly random number when I got mine.
> > 
> > 
> > Great! If you want you can peer review the theme before I merge just to double check if it works correctly, otherwise I can merge the PR and close the issue now :).
> 
> Looks good to me!

Neato! I will merge now, If you have anymore issues feel free to reach out. :)
