### ISSUE TITLE
Add corfu support

### ISSUE THREAD

**Issue by thestranger104** [catppuccin/emacs#58]
[Corfu](https://github.com/minad/corfu) popups doesn't follow theme. Not an issue with company-mode.
![Screenshot_2023-02-07_12-19-47](https://user-images.githubusercontent.com/111840273/217164514-586195bc-3349-42d4-92a6-eaa5ef4599cf.png)

**Comment by nyxkrage** [comment]
Corfu should now properly follow the theme
