### ISSUE TITLE
Bad contrast in `counsel-find-file`

### ISSUE THREAD

**Issue by noaccOS** [catppuccin/emacs#6]
![image](https://user-images.githubusercontent.com/24324352/171630129-8b7c75a8-9ae0-4a8e-b76c-f8da7393ea4a.png)

The selected item has pink foreground color which is hard to read on the green background for the search

Note: the install is a clean emacs instance in which I 
1. added melpa
2. installed catppuccin and counsel
3. `(load-theme 'catppuccin)`
4. `M-x counsel-find-file`

**Comment by NamesCode** [comment]
Updated [colour palette](https://github.com/catppuccin/emacs/commit/765293325d91abe891335b55ad8c3ea3dd4b471b) so I am unsure if this is still an issue. If it is I will reopen issue.
