### ISSUE TITLE
highlight-indentation-mode and subtext1

### ISSUE THREAD

**Issue by martin-volf** [catppuccin/emacs#72]
The color `subtext1` is quite dark compared to the background in the latte flavor (or quite light for other flavors) which is probably fine for most uses of that color, but it is also used for `highlight-indentation-face` and that is causing distracting vertical bars in `highlight-indentation-mode`:
![catp-latte](https://user-images.githubusercontent.com/2805972/221187452-bcfd86ac-fd20-4469-bec8-f9cc562dfb23.png)

This is how it looks with the default theme:
![default](https://user-images.githubusercontent.com/2805972/221187573-b8090e06-7d67-4d3d-b293-ffaf374424ea.png)

**Comment by NamesCode** [comment]
If you set line 533 to 
```
(highlight-indentation-face :background ,ctp-overlay0)
``` does it look any better? (I'm unable to test it myself rn, soz)

**Comment by martin-volf** [comment]
Somewhat, but it is still quite distracting.  From the list of named colors, only `mantle` and `crust` are good (even though they are darker than `base` in the dark variants, but that does not matter much), `surface0` is acceptable.

**Comment by NamesCode** [comment]
Which do you prefer Mantle or crust?

**Comment by martin-volf** [comment]
I think I prefer `mantle` - it is closer to `base` but still easily discernible.

**Comment by NamesCode** [comment]
👍  committing now
