### ISSUE TITLE
Theme hides icons in lsp-headerline-breadcrumbs

### ISSUE THREAD

**Issue by umgefahren** [catppuccin/emacs#73]
If I remove the theme and use a default doom emacs one, the icons are there. With this, they are just gone. I don't know why though.

**Comment by NamesCode** [comment]
Could You send an image of this happening?

**Comment by NamesCode** [comment]
Hey, just checking if this is still an issue?

**Comment by umgefahren** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/55623006/232299458-ca94da85-aeb1-4a10-be6e-98059483a89b.png">
Sorry I forgot. It looks like this.

**Comment by umgefahren** [comment]
It would be great if you could resolve it!

**Comment by KaranAhlawat** [comment]
@umgefahren Hello, would it be possible to provide a minimal reproducible config for this issue? Would help with figuring out what's going wrong.
