### ISSUE TITLE
Table's contrast in org-mode is too low

### ISSUE THREAD

**Issue by c-my** [catppuccin/emacs#74]
![image](https://user-images.githubusercontent.com/22538534/226158522-21c409c6-a3b8-4395-a6b9-f1f3d133ca06.png)

**Comment by NamesCode** [comment]
Would overlay1 work? 
<img width="129" alt="image" src="https://user-images.githubusercontent.com/86119896/227341624-762f6d57-e500-4d98-bfed-bb6afd9d194b.png">

**Comment by c-my** [comment]
Sorry I'm a newbie in Emacs. But how can I check whether the overlay1 work?

**Comment by NamesCode** [comment]
No need to check, the image i've attached in my message has overlay1 set as the colour for the table. How have you been enjoying emacs?

**Comment by c-my** [comment]
Thanks for your reply. I'm using doom Emacs and  enjoying the org mode. 😄
So how can I set overlay1 for the table color? And is this a bug need to fix or should I just close this issue?

**Comment by NamesCode** [comment]
If you open the theme file in emacs and hit `C-s org-table` change the ,ctp-surface2 to ,ctp-overlay1

**Comment by NamesCode** [comment]
Hey, Just checking if this is still an issue?

**Comment by c-my** [comment]
Sorry, I will close this issue now.
