### ISSUE TITLE
`current` background too close to `base` in latte flavor

### ISSUE THREAD

**Issue by byronclark** [catppuccin/emacs#75]
Here's what the `highlight` face currently looks like in latte flavor. The background is `ctp-current`.
![image](https://user-images.githubusercontent.com/61418/227752745-b37f48d3-f2ae-4e48-ba39-d6a1f561ac52.png)

At least on my screen, the highlight is impossible to distinguish because the background color for that face is too close the the background color for the rest of the window.

The current algorithm to lighten by 5% works very well for the dark variants of the themes.

For latte specifically, darkening the base color by 5% could be a good starting place for `ctp-current`. Here's what it looks like:
![image](https://user-images.githubusercontent.com/61418/227752684-9953bf68-597d-408e-bcf4-53b509bea45f.png)

**Comment by NamesCode** [comment]
Damn latte, I will defo amend this since it looks completely unusable in the latte theme

**Comment by NamesCode** [comment]
I will close since you made a pr ❤️
