### ISSUE TITLE
Make org headings more varried in color

### ISSUE THREAD

**Issue by LonelyMusicDisc** [catppuccin/emacs#80]
It feels weird to have fun, colorful code, then going into my org file and have it look almost monotone.

**Comment by NamesCode** [comment]
I have setup in my config and forgot to merge it lol.
I have now merged it into main so if you download the latest theme it should have it :D

**Comment by NamesCode** [comment]
<img width="177" alt="image" src="https://user-images.githubusercontent.com/86119896/232253452-900a4497-9995-4f16-a575-af81eb1f671c.png">
