### ISSUE TITLE
Background is base when using "peek implementations" of lsp-mode

### ISSUE THREAD

**Issue by LionyxML** [catppuccin/emacs#95]
Thanks for bringing this awesome theme to Emacs! Please take my notes kindly. I really like this theme and my worries are for the best :)

Recently on default theme some changes made it really strange to use. It was a major changer for me :(

I think most came from this commit:
https://github.com/catppuccin/emacs/commit/8aae242e95e908dc6007212e5c451d8197b43179

On swiper I now have a huge red bar hurting my eyes all over my monitor whenever I use it:
<img width="1440" alt="image" src="https://github.com/catppuccin/emacs/assets/16169950/f238bbe9-1415-4122-8211-b6a36bdbb51c">

It used to be:
<img width="1440" alt="image" src="https://github.com/catppuccin/emacs/assets/16169950/694133b3-2377-4f6c-b024-c5cb2ca46057">

On counsel git grep:

it used to be:
<img width="1440" alt="image" src="https://github.com/catppuccin/emacs/assets/16169950/f9c6fd88-8770-443a-a1a0-12fc3278ae66">

Now this red really contrasts (imho for no reason, since the blue bar was the color for matchings (bg, fg, inverted) and now it looks like a stack of bars trying to get for attention):
<img width="1440" alt="image" src="https://github.com/catppuccin/emacs/assets/16169950/cee80c09-7a90-4613-a501-7c06a2c2a74c">

Now a major issue:

While using it with lsp-mode it is almost impossible to "peek implementations".

Example with gotham, you should be able to see the implementation like this:
<img width="1438" alt="image" src="https://github.com/catppuccin/emacs/assets/16169950/64cddc69-3590-4ed7-abd2-e45453988ebd">

Same with `atom-one-dark`:
<img width="1440" alt="image" src="https://github.com/catppuccin/emacs/assets/16169950/52d1adac-c487-460b-a819-c608e998f6d5">

But with my favorite theme catppuccin, I cannot distinguish backgrounds:
on old bluish:
<img width="1440" alt="image" src="https://github.com/catppuccin/emacs/assets/16169950/dbcbdfdd-7e5c-4f2f-8394-84d70615a8f8">

on now redish:
<img width="1440" alt="image" src="https://github.com/catppuccin/emacs/assets/16169950/ace464fb-f1bc-4904-8256-2d7e51029a91">

It looked like a blueish catppuccin, now its a redish catppuccin. I feel like I lost my cat :( please don't make swipe red bar default.

**Comment by LionyxML** [comment]
Also what I meant by "default" was Mocha variation.

Like here: https://github.com/catppuccin/emacs/blob/main/assets/Mocha.webp

No red bars :)

**Comment by nyxkrage** [comment]
Hey 👋 

Sadly the red for matching is for now here to stay, as this is what the [theme-wide style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md) has landed on. Feel free to open an issue on the main repo about the selection highlight colors, if you don't feel like they should be the red.

You should be able to get back to the old blue behavior by doing
```lisp
(custom-set-faces `(show-paren-mismatch ((t (:foreground ,(catppuccin-get-color 'blue))))))
```

Though the background while peeking implementations definitely seems like a bug!
I'll rename the issue to reflect that it will just be about the wrong background color.

**Comment by LionyxML** [comment]
@nyxkrage thanks for your prompt response!

I can confirm this is beautiful for LSP now:
![image](https://github.com/catppuccin/emacs/assets/16169950/e7c9f0ed-2700-4a4a-b106-d107e07b1436)

Well, I can see red for matching things on text while searching, but not on choice menus "selection".

I tried your solution, it works fine, and i'll replicate it to other places, thanks!

I'll open another bug report later regarding some strange behavior with company-mode, I hope you're ok with me opening bug reports :P
